// <auto-generated/>
#pragma warning disable CS0618
using GitHub.Enterprises.Item.NetworkSettings.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.Enterprises.Item.NetworkSettings
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\network-settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class NetworkSettingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the GitHub.enterprises.item.networkSettings.item collection</summary>
        /// <param name="position">Unique identifier of the hosted compute network settings.</param>
        /// <returns>A <see cref="global::GitHub.Enterprises.Item.NetworkSettings.Item.WithNetwork_settings_ItemRequestBuilder"/></returns>
        public global::GitHub.Enterprises.Item.NetworkSettings.Item.WithNetwork_settings_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("network_settings_id", position);
                return new global::GitHub.Enterprises.Item.NetworkSettings.Item.WithNetwork_settings_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Enterprises.Item.NetworkSettings.NetworkSettingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NetworkSettingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/network-settings", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Enterprises.Item.NetworkSettings.NetworkSettingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NetworkSettingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/network-settings", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
