// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Orgs.Item.AuditLog {
    #pragma warning disable CS1591
    public enum GetIncludeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "web")]
        #pragma warning disable CS1591
        Web,
        #pragma warning restore CS1591
        [EnumMember(Value = "git")]
        #pragma warning disable CS1591
        Git,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
