// <auto-generated/>
#pragma warning disable CS0618
using GitHub.Enterprises.Item.Actions;
using GitHub.Enterprises.Item.Announcement;
using GitHub.Enterprises.Item.AuditLog;
using GitHub.Enterprises.Item.CodeScanning;
using GitHub.Enterprises.Item.Code_security_and_analysis;
using GitHub.Enterprises.Item.ConsumedLicenses;
using GitHub.Enterprises.Item.Copilot;
using GitHub.Enterprises.Item.Dependabot;
using GitHub.Enterprises.Item.Item;
using GitHub.Enterprises.Item.LicenseSyncStatus;
using GitHub.Enterprises.Item.SecretScanning;
using GitHub.Enterprises.Item.Settings;
using GitHub.Enterprises.Item.Team;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.Enterprises.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class WithEnterpriseItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The actions property</summary>
        public global::GitHub.Enterprises.Item.Actions.ActionsRequestBuilder Actions
        {
            get => new global::GitHub.Enterprises.Item.Actions.ActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The announcement property</summary>
        public global::GitHub.Enterprises.Item.Announcement.AnnouncementRequestBuilder Announcement
        {
            get => new global::GitHub.Enterprises.Item.Announcement.AnnouncementRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auditLog property</summary>
        public global::GitHub.Enterprises.Item.AuditLog.AuditLogRequestBuilder AuditLog
        {
            get => new global::GitHub.Enterprises.Item.AuditLog.AuditLogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The code_security_and_analysis property</summary>
        public global::GitHub.Enterprises.Item.Code_security_and_analysis.Code_security_and_analysisRequestBuilder Code_security_and_analysis
        {
            get => new global::GitHub.Enterprises.Item.Code_security_and_analysis.Code_security_and_analysisRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The codeScanning property</summary>
        public global::GitHub.Enterprises.Item.CodeScanning.CodeScanningRequestBuilder CodeScanning
        {
            get => new global::GitHub.Enterprises.Item.CodeScanning.CodeScanningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The consumedLicenses property</summary>
        public global::GitHub.Enterprises.Item.ConsumedLicenses.ConsumedLicensesRequestBuilder ConsumedLicenses
        {
            get => new global::GitHub.Enterprises.Item.ConsumedLicenses.ConsumedLicensesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The copilot property</summary>
        public global::GitHub.Enterprises.Item.Copilot.CopilotRequestBuilder Copilot
        {
            get => new global::GitHub.Enterprises.Item.Copilot.CopilotRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dependabot property</summary>
        public global::GitHub.Enterprises.Item.Dependabot.DependabotRequestBuilder Dependabot
        {
            get => new global::GitHub.Enterprises.Item.Dependabot.DependabotRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The licenseSyncStatus property</summary>
        public global::GitHub.Enterprises.Item.LicenseSyncStatus.LicenseSyncStatusRequestBuilder LicenseSyncStatus
        {
            get => new global::GitHub.Enterprises.Item.LicenseSyncStatus.LicenseSyncStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secretScanning property</summary>
        public global::GitHub.Enterprises.Item.SecretScanning.SecretScanningRequestBuilder SecretScanning
        {
            get => new global::GitHub.Enterprises.Item.SecretScanning.SecretScanningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::GitHub.Enterprises.Item.Settings.SettingsRequestBuilder Settings
        {
            get => new global::GitHub.Enterprises.Item.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team property</summary>
        public global::GitHub.Enterprises.Item.Team.TeamRequestBuilder Team
        {
            get => new global::GitHub.Enterprises.Item.Team.TeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the GitHub.enterprises.item.item collection</summary>
        /// <param name="position">The security feature to enable or disable.</param>
        /// <returns>A <see cref="global::GitHub.Enterprises.Item.Item.WithSecurity_productItemRequestBuilder"/></returns>
        public global::GitHub.Enterprises.Item.Item.WithSecurity_productItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("security_product", position);
                return new global::GitHub.Enterprises.Item.Item.WithSecurity_productItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Enterprises.Item.WithEnterpriseItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnterpriseItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Enterprises.Item.WithEnterpriseItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnterpriseItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
