// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    /// <summary>Authentication Type for Amazon S3.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public enum AmazonS3OidcConfig_authentication_type
    {
        [EnumMember(Value = "oidc")]
        #pragma warning disable CS1591
        Oidc,
        #pragma warning restore CS1591
    }
}
