// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    /// <summary>The response status to the bypass request until dismissed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public enum BypassResponse_status
    {
        [EnumMember(Value = "approved")]
        #pragma warning disable CS1591
        Approved,
        #pragma warning restore CS1591
        [EnumMember(Value = "denied")]
        #pragma warning disable CS1591
        Denied,
        #pragma warning restore CS1591
        [EnumMember(Value = "dismissed")]
        #pragma warning disable CS1591
        Dismissed,
        #pragma warning restore CS1591
    }
}
