// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    /// <summary>Datadog Site to use.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public enum DatadogConfig_site
    {
        [EnumMember(Value = "US")]
        #pragma warning disable CS1591
        US,
        #pragma warning restore CS1591
        [EnumMember(Value = "US3")]
        #pragma warning disable CS1591
        US3,
        #pragma warning restore CS1591
        [EnumMember(Value = "US5")]
        #pragma warning disable CS1591
        US5,
        #pragma warning restore CS1591
        [EnumMember(Value = "EU1")]
        #pragma warning disable CS1591
        EU1,
        #pragma warning restore CS1591
        [EnumMember(Value = "US1-FED")]
        #pragma warning disable CS1591
        US1FED,
        #pragma warning restore CS1591
        [EnumMember(Value = "AP1")]
        #pragma warning disable CS1591
        AP1,
        #pragma warning restore CS1591
    }
}
