// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models {
    /// <summary>A type of a resource</summary>
    public enum Meta_resourceType
    {
        [EnumMember(Value = "User")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "Group")]
        #pragma warning disable CS1591
        Group,
        #pragma warning restore CS1591
    }
}
