// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum PatchSchema_schemas
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "urn:ietf:params:scim:api:messages:2.0:PatchOp")]
        #pragma warning disable CS1591
        UrnIetfParamsScimApiMessages20PatchOp,
        #pragma warning restore CS1591
    }
}
