// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public partial class PushRuleBypassRequest_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the ruleset for the rules that were violated.</summary>
        public int? RulesetId { get; set; }
        /// <summary>The name of the ruleset for the rules that were violated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RulesetName { get; set; }
#nullable restore
#else
        public string RulesetName { get; set; }
#endif
        /// <summary>The type of rule that was violated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuleType { get; set; }
#nullable restore
#else
        public string RuleType { get; set; }
#endif
        /// <summary>The number of rule violations generated from the push associated with this request.</summary>
        public int? TotalViolations { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Models.PushRuleBypassRequest_data"/> and sets the default values.
        /// </summary>
        public PushRuleBypassRequest_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.Models.PushRuleBypassRequest_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.Models.PushRuleBypassRequest_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHub.Models.PushRuleBypassRequest_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "rule_type", n => { RuleType = n.GetStringValue(); } },
                { "ruleset_id", n => { RulesetId = n.GetIntValue(); } },
                { "ruleset_name", n => { RulesetName = n.GetStringValue(); } },
                { "total_violations", n => { TotalViolations = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("ruleset_id", RulesetId);
            writer.WriteStringValue("ruleset_name", RulesetName);
            writer.WriteStringValue("rule_type", RuleType);
            writer.WriteIntValue("total_violations", TotalViolations);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
