// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace GitHub.Models {
    #pragma warning disable CS1591
    public class ScimEnterpriseUserList : IAdditionalDataHolder, IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of objects per page</summary>
        public int? ItemsPerPage { get; set; }
        /// <summary>Information about each provisioned account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ScimEnterpriseUserResponse>? Resources { get; set; }
#nullable restore
#else
        public List<ScimEnterpriseUserResponse> Resources { get; set; }
#endif
        /// <summary>The URIs that are used to indicate the namespaces of the list SCIM schemas.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<ScimEnterpriseUserList_schemas?>? Schemas { get; set; }
#nullable restore
#else
        public List<ScimEnterpriseUserList_schemas?> Schemas { get; set; }
#endif
        /// <summary>A starting index for the returned page</summary>
        public int? StartIndex { get; set; }
        /// <summary>Number of results found</summary>
        public int? TotalResults { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="ScimEnterpriseUserList"/> and sets the default values.
        /// </summary>
        public ScimEnterpriseUserList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="ScimEnterpriseUserList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ScimEnterpriseUserList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ScimEnterpriseUserList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"itemsPerPage", n => { ItemsPerPage = n.GetIntValue(); } },
                {"Resources", n => { Resources = n.GetCollectionOfObjectValues<ScimEnterpriseUserResponse>(ScimEnterpriseUserResponse.CreateFromDiscriminatorValue)?.ToList(); } },
                {"schemas", n => { Schemas = n.GetCollectionOfEnumValues<ScimEnterpriseUserList_schemas>()?.ToList(); } },
                {"startIndex", n => { StartIndex = n.GetIntValue(); } },
                {"totalResults", n => { TotalResults = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("itemsPerPage", ItemsPerPage);
            writer.WriteCollectionOfObjectValues<ScimEnterpriseUserResponse>("Resources", Resources);
            writer.WriteCollectionOfEnumValues<ScimEnterpriseUserList_schemas>("schemas", Schemas);
            writer.WriteIntValue("startIndex", StartIndex);
            writer.WriteIntValue("totalResults", TotalResults);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
