// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    /// <summary>Shows if a package system is enabled, disabled, or read-only in a GHES installation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public enum ServerStatisticsPackages_ecosystems_enabled
    {
        [EnumMember(Value = "TRUE")]
        #pragma warning disable CS1591
        TRUE,
        #pragma warning restore CS1591
        [EnumMember(Value = "FALSE")]
        #pragma warning disable CS1591
        FALSE,
        #pragma warning restore CS1591
        [EnumMember(Value = "READONLY")]
        #pragma warning disable CS1591
        READONLY,
        #pragma warning restore CS1591
    }
}
