// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public partial class ServerStatistics_ghe_stats_pulls : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The mergeable_pulls property</summary>
        public int? MergeablePulls { get; set; }
        /// <summary>The merged_pulls property</summary>
        public int? MergedPulls { get; set; }
        /// <summary>The total_pulls property</summary>
        public int? TotalPulls { get; set; }
        /// <summary>The unmergeable_pulls property</summary>
        public int? UnmergeablePulls { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Models.ServerStatistics_ghe_stats_pulls"/> and sets the default values.
        /// </summary>
        public ServerStatistics_ghe_stats_pulls()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.Models.ServerStatistics_ghe_stats_pulls"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.Models.ServerStatistics_ghe_stats_pulls CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHub.Models.ServerStatistics_ghe_stats_pulls();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "mergeable_pulls", n => { MergeablePulls = n.GetIntValue(); } },
                { "merged_pulls", n => { MergedPulls = n.GetIntValue(); } },
                { "total_pulls", n => { TotalPulls = n.GetIntValue(); } },
                { "unmergeable_pulls", n => { UnmergeablePulls = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("mergeable_pulls", MergeablePulls);
            writer.WriteIntValue("merged_pulls", MergedPulls);
            writer.WriteIntValue("total_pulls", TotalPulls);
            writer.WriteIntValue("unmergeable_pulls", UnmergeablePulls);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
