// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum User_schemas
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "urn:ietf:params:scim:schemas:core:2.0:User")]
        #pragma warning disable CS1591
        UrnIetfParamsScimSchemasCore20User,
        #pragma warning restore CS1591
    }
}
