// <auto-generated/>
using GitHub.EnterpriseInstallation.Item.ServerStatistics;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseInstallation.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprise-installation\{enterprise_or_org}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class WithEnterprise_or_orgItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The serverStatistics property</summary>
        public global::GitHub.EnterpriseInstallation.Item.ServerStatistics.ServerStatisticsRequestBuilder ServerStatistics
        {
            get => new global::GitHub.EnterpriseInstallation.Item.ServerStatistics.ServerStatisticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseInstallation.Item.WithEnterprise_or_orgItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnterprise_or_orgItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprise-installation/{enterprise_or_org}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseInstallation.Item.WithEnterprise_or_orgItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnterprise_or_orgItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprise-installation/{enterprise_or_org}", rawUrl)
        {
        }
    }
}
