// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Enterprises.Item.Actions.RunnerGroups
{
    /// <summary>Visibility of a runner group. You can select all organizations or select individual organization.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum RunnerGroupsPostRequestBody_visibility
    {
        [EnumMember(Value = "selected")]
        #pragma warning disable CS1591
        Selected,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
