// <auto-generated/>
using GitHub.Orgs.Item.ExternalGroup.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.Orgs.Item.ExternalGroup
{
    /// <summary>
    /// Builds and executes requests for operations under \orgs\{org}\external-group
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class ExternalGroupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the GitHub.orgs.item.externalGroup.item collection</summary>
        /// <param name="position">The unique identifier of the group.</param>
        /// <returns>A <see cref="global::GitHub.Orgs.Item.ExternalGroup.Item.WithGroup_ItemRequestBuilder"/></returns>
        public global::GitHub.Orgs.Item.ExternalGroup.Item.WithGroup_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("group_id", position);
                return new global::GitHub.Orgs.Item.ExternalGroup.Item.WithGroup_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Orgs.Item.ExternalGroup.ExternalGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExternalGroupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/external-group", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Orgs.Item.ExternalGroup.ExternalGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExternalGroupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/external-group", rawUrl)
        {
        }
    }
}
