// <auto-generated/>
using GitHub.EnterpriseInstallation.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseInstallation {
    /// <summary>
    /// Builds and executes requests for operations under \enterprise-installation
    /// </summary>
    public class EnterpriseInstallationRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the GitHub.enterpriseInstallation.item collection</summary>
        /// <param name="position">The slug version of the enterprise name or the login of an organization.</param>
        /// <returns>A <see cref="WithEnterprise_or_orgItemRequestBuilder"/></returns>
        public WithEnterprise_or_orgItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("enterprise_or_org", position);
                return new WithEnterprise_or_orgItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="EnterpriseInstallationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnterpriseInstallationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprise-installation", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="EnterpriseInstallationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnterpriseInstallationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprise-installation", rawUrl)
        {
        }
    }
}
