// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Repos.Item.Item.BypassRequests.SecretScanning.Item
{
    /// <summary>The review action to perform on the bypass request.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public enum WithBypass_request_numberPatchRequestBody_status
    {
        [EnumMember(Value = "approve")]
        #pragma warning disable CS1591
        Approve,
        #pragma warning restore CS1591
        [EnumMember(Value = "reject")]
        #pragma warning disable CS1591
        Reject,
        #pragma warning restore CS1591
    }
}
