// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.Teams.Item.TeamSync.GroupMappings
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public partial class GroupMappingsPatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The IdP groups you want to connect to a GitHub team. When updating, the new `groups` object will replace the original one. You must include any existing groups that you don&apos;t want to remove.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHub.Teams.Item.TeamSync.GroupMappings.GroupMappingsPatchRequestBody_groups>? Groups { get; set; }
#nullable restore
#else
        public List<global::GitHub.Teams.Item.TeamSync.GroupMappings.GroupMappingsPatchRequestBody_groups> Groups { get; set; }
#endif
        /// <summary>The synced_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SyncedAt { get; set; }
#nullable restore
#else
        public string SyncedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Teams.Item.TeamSync.GroupMappings.GroupMappingsPatchRequestBody"/> and sets the default values.
        /// </summary>
        public GroupMappingsPatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.Teams.Item.TeamSync.GroupMappings.GroupMappingsPatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.Teams.Item.TeamSync.GroupMappings.GroupMappingsPatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHub.Teams.Item.TeamSync.GroupMappings.GroupMappingsPatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "groups", n => { Groups = n.GetCollectionOfObjectValues<global::GitHub.Teams.Item.TeamSync.GroupMappings.GroupMappingsPatchRequestBody_groups>(global::GitHub.Teams.Item.TeamSync.GroupMappings.GroupMappingsPatchRequestBody_groups.CreateFromDiscriminatorValue)?.AsList(); } },
                { "synced_at", n => { SyncedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::GitHub.Teams.Item.TeamSync.GroupMappings.GroupMappingsPatchRequestBody_groups>("groups", Groups);
            writer.WriteStringValue("synced_at", SyncedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
