// <auto-generated/>
using GitHub.Scim.V2.Enterprises.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace GitHub.Scim.V2.Enterprises {
    /// <summary>
    /// Builds and executes requests for operations under \scim\v2\enterprises
    /// </summary>
    public class EnterprisesRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the GitHub.scim.v2.enterprises.item collection</summary>
        /// <param name="position">The slug version of the enterprise name. You can also substitute this value with the enterprise id.</param>
        /// <returns>A <see cref="WithEnterpriseItemRequestBuilder"/></returns>
        public WithEnterpriseItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("enterprise", position);
                return new WithEnterpriseItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="EnterprisesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnterprisesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scim/v2/enterprises", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="EnterprisesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnterprisesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scim/v2/enterprises", rawUrl)
        {
        }
    }
}
