// <auto-generated/>
using GitHub.Enterprises.Item.Actions.Cache.Usage;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace GitHub.Enterprises.Item.Actions.Cache {
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\actions\cache
    /// </summary>
    public class CacheRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The usage property</summary>
        public UsageRequestBuilder Usage
        {
            get => new UsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="CacheRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CacheRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/actions/cache", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="CacheRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CacheRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/actions/cache", rawUrl)
        {
        }
    }
}
