// <auto-generated/>
using GitHub.Enterprises.Item.Actions.Cache;
using GitHub.Enterprises.Item.Actions.Oidc;
using GitHub.Enterprises.Item.Actions.Permissions;
using GitHub.Enterprises.Item.Actions.RunnerGroups;
using GitHub.Enterprises.Item.Actions.Runners;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace GitHub.Enterprises.Item.Actions {
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\actions
    /// </summary>
    public class ActionsRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The cache property</summary>
        public CacheRequestBuilder Cache
        {
            get => new CacheRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oidc property</summary>
        public OidcRequestBuilder Oidc
        {
            get => new OidcRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public PermissionsRequestBuilder Permissions
        {
            get => new PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runnerGroups property</summary>
        public RunnerGroupsRequestBuilder RunnerGroups
        {
            get => new RunnerGroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runners property</summary>
        public RunnersRequestBuilder Runners
        {
            get => new RunnersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/actions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/actions", rawUrl)
        {
        }
    }
}
